### ISSUE TITLE
Creation and Implementation of ToolTips

### ISSUE THREAD

**Issue by Cloud9-Sec** [cs481-ekh/s22-hospsim#11]
Sprint 1 - Creation and Implementation of ToolTips

- [x] - As a user, I need to be able to hover over a small image that provides information on an object such as big picture items like buttons and add staff etc. #12 
- [x] - As a user, I need to be able to understand definitions of abbreviations and various parts of the simulator  #14
- [x] -As a user, I need to be able to understand how the budget calculations are made via a ToolTip #13
- [x]  -Write out list of tooltips sentences and what they are applied to #15

**Comment by AndrewGerberBSU** [comment]
probs done
