### ISSUE TITLE
Staff Budget View 

### ISSUE THREAD

**Issue by ChinweCodes** [cs481-ekh/s22-hospsim#71]
- [ ] As a user, I need to see a button to access the budget. #74
- [ ] As a user, I need to be able to click on a button to view the budget. #72
- [ ] As a user, I need to be able to update the staff budget in a two-week period. #73 
- [ ] As a user, I need to be able to exit out of the budget when I'm done working on it. #75
